=== borjasf/examenesaadd/junio 25 mongo jsonb schema listado registrar revision converter fechas/xml/animal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="animal">
        <xs:complexType>
            <xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
                <xs:element name="especie" type="xs:string"/>
                <xs:element name="edadEntrada" type="xs:int"/>
                <xs:element name="fechaEntrada" type="xs:date"/>
                <xs:element name="adopcion" type="tipo_adopcion" minOccurs="0"/>
                <xs:element name="revisiones" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="revision" type="tipo_revision" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="tipo_adopcion">
        <xs:sequence>
            <xs:element name="fechaAdopcion" type="xs:date"/>
            <xs:element name="nombreAdoptante" type="xs:string"/>
            <xs:element name="telefono" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

   <xs:complexType name="tipo_revision">
        <xs:sequence>
            <xs:element name="fecha" type="xs:date"/>
            <xs:element name="peso" type="xs:double"/>
            <xs:element name="observaciones" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== borjasf/examenesaadd/junio 25 mongo jsonb schema listado registrar revision converter fechas/xml/animal.xml
<?xml version="1.0" encoding="UTF-8"?>
<animal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="animal.xsd"
      id="123123214s">
    <nombre>Juan</nombre>
   	<especie>Caballo</especie>
   	<edadEntrada>24</edadEntrada>
   	<fechaEntrada>2025-10-01</fechaEntrada>
   	<adopcion>
   	<fechaAdopcion>2025-12-01</fechaAdopcion>
   	<nombreAdoptante>Samuel</nombreAdoptante>
   	<telefono>123456789</telefono>
   	</adopcion>
   	<revisiones>
   	<revision>
   	<fecha>2025-12-31</fecha>
   	<peso>125.1</peso>
   	<observaciones>observacion</observaciones>
   	</revision>
   	
   	</revisiones>
</animal>
